/******************************************************************************************************
* This file is part of the Nebula Trigger Handler project, released under the MIT License.            *
* See LICENSE file or go to https://github.com/jongpie/NebulaTriggerHandler for full license details. *
******************************************************************************************************/
@isTest
private class TriggerFilteredSObjectHandler_Tests {

    @isTest
    static void i_should_write_tests() {
        System.assert(false, 'Write some tests!!');
    }

}